### ISSUE TITLE
Contribute to `fastify-redis`?

### ISSUE THREAD

**Issue by jsumners** [wotermelon/fastify-ioredisjs#1]
I think it would be fantastic if you contributed a PR to https://github.com/fastify/fastify-redis that allows the user to decide which client to use within a single module. For example:

```js
fastify.register(require('fastify-redis'), {ioredis: true})
```

cc: @delvedor

**Comment by delvedor** [comment]
Yeah, it would be awesome.
I think that the api should be something like the following:
```js
fastify.register(
  require('fastify-redis'),
  { driver: require('ioredis') }
)
```
